### ISSUE TITLE
Zoomoljunk ki a térkép alapértelmezett nézetében

### ISSUE THREAD

**Issue by Cooty** [Code-for-Hungary/nerhotel#12]
Ha most megnyitom a [nerhotel.hu](https://nerhotel.hu)-t, akkor Budapest kelős közepére vagyok bezoomolva, ahol van tizenvalahány pin. Ellenben az egész alkalmazásban több száz hely van már felvéve, még Romániában és Ausztriában is vannak helyek. A mostani nézet azt a illúziót keltheti, hogy ez valami "pesti" dolog, holott korántsem.

Javaslom, hogy alapból vegyük kisebbre a térkép zoomját úgy hogy egész Magyarországot látja a user rögtön (és aztán kedve szerint rázoomolhat arra a régióra amire ő kíváncsi).

Valahogy így mondjuk:

![image](https://user-images.githubusercontent.com/6146591/205500399-ec317abe-8236-4280-b4ab-f0bb6801ef87.png)

**Comment by Cooty** [comment]
@pisipite - Mi a véleményed erről?

**Comment by pisipite** [comment]
jogos! egyetértek, hogy kb. ez a tág-Magyarországnyi nézet a legpraktikusabb.
