### ISSUE TITLE
Az oldal címsora nem frissül

### ISSUE THREAD

**Issue by Cooty** [Code-for-Hungary/nerhotel#13]
![image](https://user-images.githubusercontent.com/6146591/205501251-9d3e0442-81d9-422c-917a-f6d20ce15d03.png)

Amikor navigálok az oldalon akkor a böngésző tabban látható cím (`<title>`) mindig ugyanaz ("Kinél cseng a kassza? - NER Hotel").

Javaslom, hogy mindig az adott aloldalon kiírt cím plusz az oldal neve legyen beállítva, amikor navigálok.

pl [ezen az oldalon](https://www.nerhotel.hu/#/hotel/159), annak kéne lennie, hogy "Galagonyás vendégház - NER Hotel".

**Comment by Cooty** [comment]
@pisipite - Mit gondolsz erről? Nem egy nagy munka-befektetés, de egy kicsit tud dobni az accessibility-n / usability-n. (SEO-n nem igazán, meg pl ha Facebookon megosztasz egy aloldalt akkor is sajnos a default title fog megjelenni, mert mindent JS-ből, kliens oldalon renderelünk, szóval ahhoz, hogy az FB crawler is más title-t írjon ki a link előnézetében teljesen át kéne alakítani az oldal architechtúráját...)

**Comment by pisipite** [comment]
szuper!
legtöbbet a személyek oldalt linkeljük ([pl](https://www.nerhotel.hu/#/person/Botty%C3%A1n%20Istv%C3%A1n).), általában Facebookon, ott tuti hasznos lenne a preview bármilyen szintű aktualizálása.

**Comment by pisipite** [comment]
okés, jó így!

**Comment by pisipite** [comment]
illetve a [preview](https://nerhotel-git-feat-i18n-adding-en-c4hu.vercel.app/)-nél vettem még észre, hogy az angolra váltásnál is a magyar címsor marad.
`Kinél cseng a kassza? - NER Hotel` ebből legyen `Who gets the profit? - NER Hotel`

**Comment by Cooty** [comment]
Ohh valóban erre nem is gondoltam, akkor ennyi erővel ezt a feature-t is be lehet venni az internationalization alá, mert úgyis meg kell hozzá csinálni.

**Comment by Cooty** [comment]
@pisipite - Ezt is hozzácsaptam az i18n-es Pull Requesthez. [Itt lehet megnézni](https://nerhotel-3gc265gg3-c4hu.vercel.app/) a legújabb verziót.

**Comment by pisipite** [comment]
@Cooty , az lehet, hogy ennél az átalakítás miatt eltűnt a Link Preview kép? `og:image`-ként ez van beállítva `https://www.nerhotel.hu/nh-cover.png`, viszont a [facebook debuggerben](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.nerhotel.hu%2F) (és megosztáskor) szürke üresség jelenik meg.

**Comment by Cooty** [comment]
Nem hiszem, hogy emiatt tört volna el. Ha berakom a böngészőbe a kép URL-jét (https://www.nerhotel.hu/nh-cover.png) akkor nekem megnyit egy hatalmas (3600x1950px) képet. Szóval akkor ezt az FB crawlerjének is látnia kell. Lehet, hogy ez a kép túl nagy.

Mellesleg kérlek ha bármi bugot észlesz arra nyiss egy új issue-t!

**Comment by Cooty** [comment]
@pisipite https://neilpatel.com/blog/open-graph-meta-tags/#:~:text=The%20most%20frequently%20recommended%20resolution,exceed%20the%205MB%20size%20limit.

> The most frequently recommended resolution for an OG image is 1200 pixels x 627 pixels (1.91/1 ratio). At this size, your thumbnail will be big and stand out from the crowd. Just don’t exceed the 5MB size limit.

5MB-t ugyan nem haladja meg. De azt látom, hogy ez egy részben transzparens hátterű PNG, lehet hogy azt az FB nem szereti.

![image](https://user-images.githubusercontent.com/6146591/221361820-091a8e67-e59c-4937-8147-3b5a9a208cae.png)

Javaslom ments ebből el egy fehér hátterű JPG-t 1200x627-os méretben, töltsd fel Gitbe és próbáéljuk meg azzal.

**Comment by Cooty** [comment]
@pisipite - Láttam felraktál egyet a repo gyökérkönyvtárába, de a build nem azt használja és nem azt rakja ki a szerverre. Kérlek azt töröld. A kép a `/public` mappában lakik, onnan rakja át a build folyamat a `/dist` mappába (amit itt Githubon nem fogsz látni mert nincs verziókezelés alatt) és az kerül ki a szerverre.

**Comment by pisipite** [comment]
oks, kösz! így tettem ([kicsinyítettem, public-ba raktam](https://nerhotel.hu/nh-cover.png), frissítettem debuggerben), de még mindig nem jó :/

**Comment by Cooty** [comment]
Sikerült működésre bírnom (csak a debuggerben néztem, nem csináltam valódi megosztást FB-n). Az volt a trükk, hogy átneveztem a file-t jpg-re és így már müxik...

Az persze rejtély, hogy eddig miért működött illetve a Facebook [saját dokumentációja](https://developers.facebook.com/docs/sharing/webmasters/images/) sehol nem említi, hogy ne támogatnák a PNG formátumot a megosztási képekben, de a Facebook útjai kifürkészhetetlenek...

![image](https://user-images.githubusercontent.com/6146591/221601191-9ff7ebb5-f7aa-4e6e-96a3-99e46949871c.png)

**Comment by pisipite** [comment]
működik, nagyon jó vagy!
