### ISSUE TITLE
Vercel credit hozzáadása

### ISSUE THREAD

**Issue by gazdagergo** [Code-for-Hungary/nerhotel#14]
A nerhotel.hu oldalon (láblécben, ha van ilyen) meg kell jelenítenünk a "powered by vercel" logót. Ez a felétele az open-source használatnak.

**Comment by Cooty** [comment]
Ok, ez megoldható! Honnan lehet ezt a logót letölteni? Mondjuk az a probléma, hogy jelenleg nincs footer. És a főoldalon nem is igazán lehet footert csinálni, mert ugye egy fix pozíciós térkép az egész amin navigálsz.

Két megoldást látok:

1) A főoldalon a térkép felett a bal also sarokban fix pozícióval rakjuk oda, az aloldalakon ahol meg lehet scrollozni, csinálunk egy footert.
2) A navigációs drawerbe rakjuk be a cím alá.
![image](https://user-images.githubusercontent.com/6146591/205590991-89aea6ea-f67f-4413-8146-04250df377b5.png)

A 2) egyszerűbb lenne, de nem tudom, hogy az úgy oké-e a Vercelnek, mert ugye akkor nem lesz mindig látható csak ha a user megnyitja a navigációt.

**Comment by pisipite** [comment]
mai callon abban maradtunk, hogy a kettes verzió legyen.
köszi!
