### ISSUE TITLE
tartalom többnyelvűsítése

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/nerhotel#31]
az [adatbázisból](https://docs.google.com/spreadsheets/d/1FaeML93U76Fjh9GR7gbQhtb2O3Ga0ZY2honrYKyQQLo/edit#gid=0) a `details`	és a `loc_name` tartalmaz olyan tartalmat, amit fordítani kell. ezek számára beraktam egy `details_en` és `loc_name_en` oszlopokat a spreadsheetbe.
a fordítást külön fülön ([szótár](https://docs.google.com/spreadsheets/d/1FaeML93U76Fjh9GR7gbQhtb2O3Ga0ZY2honrYKyQQLo/edit#gid=1938778598)) végezzük, ahonnan vlookup képlettel áthúzza a mezők tartalmát.

**Comment by pisipite** [comment]
a személyek adatlapján a K-Monitor adatbázis link magyar nyelvű oldalra visz. itt szuper lenne beállítani, hogy az angol nyelvű oldalról google translate-es oldalra vigyen (pl.: https://adatbazis-k--monitor-hu.translate.goog/adatbazis/cimkek/scheer-sandor?_x_tr_sl=hu&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp).
(dolgozunk az angol nyelvű életrajzokon, előbb utóbb a google translate helyett lehet majd adatbázis angol nyelvű oldalára link. ezeknek várhatóan https://adatbazis.k-monitor.hu/database/tags/scheer-sandor lesz a formátuma.)

**Comment by pisipite** [comment]
- [ ] a személyek adatlapon angol nézetben van még olyan More information, ahol a `details_en` helyett a `details` (angol helyett magyar szöveg) jelenik meg ([pl.](https://www.nerhotel.hu/#/person/M%C3%A9sz%C3%A1ros%20L%C5%91rinc?plang=en)).

**Comment by Cooty** [comment]
> * [x]  a személyek adatlapon angol nézetben van még olyan More information, ahol a `details_en` helyett a `details` (angol helyett magyar szöveg) jelenik meg ([pl.](https://www.nerhotel.hu/#/person/M%C3%A9sz%C3%A1ros%20L%C5%91rinc?plang=en)). itt is az lenne a jó, ha nincs szöveg a `details_en` mezőben, akkor ne jelenjen meg semmi.

fix #39

**Comment by Cooty** [comment]
> * [x]  a személyek adatlapján a K-Monitor adatbázis link magyar nyelvű oldalra visz. itt szuper lenne beállítani, hogy az angol nyelvű oldalról google translate-es oldalra vigyen (pl.: https://adatbazis-k--monitor-hu.translate.goog/adatbazis/cimkek/scheer-sandor?_x_tr_sl=hu&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp).
> 
> (dolgozunk az angol nyelvű életrajzokon, előbb utóbb a google translate helyett lehet majd adatbázis angol nyelvű oldalára link. ezeknek várhatóan https://adatbazis.k-monitor.hu/database/tags/scheer-sandor lesz a formátuma.)

done #40

**Comment by pisipite** [comment]
jónak tűnik mindkettő, köszi szépen!
