### ISSUE TITLE
nyelvváltó: hely leírásánál ne jelenjen meg a magyar, ha nincs angol

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/nerhotel#36]
ha van magyarszöveg egy hely leírásánál, de nincs angol (`details_en`), akkor megjeleníti a magyart (`details`). ez a hely nevénél (`loc_name_en` és `loc_name`) jó így, viszont a leírásnál nem - itt inkább ne jelenítsen meg semmit.

**Comment by pisipite** [comment]
még egy hasonló: angolul a location type-nál a `category` mező tartalma, magyarul (hely típusa) a `type` jelenjen meg.

**Comment by Cooty** [comment]
A nerhotel.hu/#/hotel/267 -vel teszteltem az elő kérést és úgy tűnik működik.
