### ISSUE TITLE
személyekről infó megjelenítése

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/nerhotel#38]
szeretnénk a személyekhez a személy adatlapján legfeljebb egy bekezdésnyi szöveget és esetleg képet megjeleníteni (mindkét nyelven). ez tippem szerint két részből áll:

- [x] adatokat egy spreadsheetből húzza be, hogy lehessen frissíteni

- [x] frontend felület kialakítása, kb. így:

![image](https://user-images.githubusercontent.com/25430950/215507772-2dd71a6f-3ee3-400b-80ff-ee96e2547249.png)

**Comment by Cooty** [comment]
Biztos, hogy Google sheetel akarjuk ezt megoldani? 

Mármint jópofa ez a google-sheet-mint-cms megoldás, de azért nem olyan jó.

Két nagy problémám van vele.

1) Nem lehet oldalanként vagy esetleg szűrőfeltételek mentén lekérni az adatokat, mint egy rendes db-ből
2) Nem lehet ID (vagy bármi más kritérium) szerint, csak egy entitást (értsd sort a táblázatból) lekérni

Mit jelent ez a gyakorlatban?

Jelenleg az összes hotelt lekérjük és kliens oldalon bent tartjuk a memóriában, amikor az oldalak közt navigálunk. Tehát amikor egy hotel (vagy személy) oldalon landol a user akkor is letöltjük neki a háttérben az összes hotelt, pedig neki csak egy kéne...

Na most akkor ehhez hozzájöne az is, hogy letöltünk neki az összes személy adatát, pedig ő csak egy oldalra kíváncsi...

Van egy javaslatom. A személyeknek csináljunk egy külön adatbázist Google [Firebasen](https://firebase.google.com/).

A firebase egy un backend-as-service szolgáltatás, aki lusta saját magának API-t írni meg DB-t üzemeltetni a frontendjéhez, az ki tudja ezt szervezni a Firebasenek. Van egy nagyon jó kis DB-jük, ami alapból generál API-t meg van egy nagyon egyszerű vizuális szerkesztő felülete, ahol be lehet vinni az adatokat (talán nem annyira felhasználóbarát mint egy spreadsheet, de kezelhető az átlagember számára is). Persze mindez nincs ingyen, de az ingyenes csomagjukban benne van minden ami nekünk kell és a felhasználók száma alapján bőven bele is férünk (https://firebase.google.com/pricing).

Aztán lehet a jövőben átmigrálhatjuk ide a hoteleket is és csinálhatunk neki egy kis mini cms-t.

A másik lehetőség, hogy kicsit jobban beleásuk magunkat a Google Sheets API-jába, mert lehet, hogy mégis meg lehet valahogy oldani, hogy csak egy sort kérjünk le egy sheetből, csak nem tudunk róla.

@pisipite / @gazdagergo - Mi a véleményetek, valami egyéb ötlet?

**Comment by pisipite** [comment]
ez szuper!
a nerhotel kezdeti tervezgetésénél rengeteget agyaltunk azon, hogy mi lenne a jó táblázat- és adatbázis kezelő a projekthez. nem ismertem eddig a Firebase-t, de az alapján, amit írsz pont ilyesmi kellene. ha kicsit írtok instrukciókat, merre induljak el, szívesen foglalkozok az adatbázis átültetésével.

**Comment by Cooty** [comment]
Én két lépésben csinálnám. Először megcsinálnám a "személyekről infó" funkciót Firebasel és a jelenlegi adatbázist nem bolygatnám (a kettő minden további nélkül tud egyszerre működni) és ha azt látjuk, hogy ez jó így akkor át lehet ültetni a hoteleket is.

Ami a migrációt illeti, ezt szkriptel kéne csinálni semmiképp sem kézzel. Alapvetően nem kéne bonyolult legyen, mert a Firebase JSON alapú DB-t használ, szóval majd ki kell menteni egy JSON-t az excelből (tahát ami az előtt volt, hogy refaktoráltam :D ) és azt be lehet küldeni a Firebase-nek API-n keresztül. De ez legyen a jövő zenéje. Mindenképp fokozatosan kell ezt csinálni.

**Comment by pisipite** [comment]
ok!
holnap délután leülünk Gergővel kipróbálni a Firebase-t. lehet, hogy írunk majd kérdéseket.

**Comment by Cooty** [comment]
@pisipite Na az van, hogy volt egy kis időm és félig megcsináltam a feladatot (jelzem a kisebbik felét...).

Csináltam egy UI-t az személynek, statikus adatokkal.

Ezen az URL-en meg is nézheted.
https://nerhotel-git-feat-add-person-info-to-ui-c4hu.vercel.app/

Persze most mindenhol Mészáros Lőri van ott tehát [itt is](https://nerhotel-git-feat-add-person-info-to-ui-c4hu.vercel.app/person/Papp%20L%C3%A1szl%C3%B3) meg [itt is](https://nerhotel-git-feat-add-person-info-to-ui-c4hu.vercel.app/person/Balog%20L%C3%A1szl%C3%B3).

A szöveget a K-Monitor adatbázis oldalról kopiztam, feltételeztem, hogy lehetnek benne akár linkek vagy HTML formázások (félkövér, dőlt betű, stb) is.

Az első kérdésem, hogy vizuálisan jó lesz ez így? (Nézd meg mobil nézetben is).

A nagyon menő dolog az, hogy mindez egy feature flag mögé van bújtatva, tehát a fent említett preview aldomainen látod míg az élesen nem. Szóval így be tudtam mergelni a változtatást a masterbe, hogy nem kell egy hónapokig lebegő feature branchet csinálnom és esetleg ha időközben valamit ki kéne rakni élesre az nem lenne blokkolva ez által.

@gazdagergo FYI a Vercel felületén a Settings alatt van a `VITE_FEATURE_FLAG_PERSON_INFO` környezeti változó ami most csak a Preview környzetekre van bepipálva, ez szabályoza ennek a doboznak a megjelenését.

**Comment by pisipite** [comment]
ú, váó, őrület! nagyon szép! vizuálisan pont így képzeltem.
mobilon is szuper. itt a térképet rögtön a személyleírás mögé venném, utána raknám a többi infót.
szövegnél valami limitet jó lenne majd belerakni, hogy pl. csak 320 karaktert szívjon át a sajtóadatbázisból (és majd próbálunk ügyelni rá, hogy az első 320 karakter önállóan értelmes legyen). 

szuper ügyes vagy!

**Comment by Cooty** [comment]
1) `itt a térképet rögtön a személyleírás mögé venném, utána raknám a többi infót.` - Ez tényleg jó lenne, de sajnos nem triviális mert a HTML szerkezete úgy van megcsinálva, hogy **1. oszlop** benne Név, Profil adatok, Kapcsolódó hotelek, **2. oszlop** benne Térkép. Mobilon pedig az 2. oszlop betörik az első alá, tehát minden ami ott van csak az első oszlop tartalma után tud jönni. Szóval a jelenlegi struktúrában sajnos nem megoldható amit kérsz. Ha nagyon fontos, akkor megpróbálhatom refaktorálni az oldal CSS/HTML-jét, de nem lenne egyszerű. Illetve tovább bonyolítja a helyzetet, hogy a Hotel aloldal is ugyanezt a CSS-t használja szóval akkor a változtatás azt az oldalt is érintené (tehát ott is a cím után jönne a térkép és aztán minden más), ha nem akarod hogy érintse akkor ketté kéne szedni ami még további refaktor még további idő...

2) `szövegnél valami limitet jó lenne majd belerakni, hogy pl. csak 320 karaktert szívjon át a sajtóadatbázisból ` - Azt mondod _"Szívjon át a sajtóadatbázisból..."_, ez azt jelenti, hogy ez adat (szöveg és profilkép) mindig a K-Monitoros Sajtóadatbázisból jönne? Mert ha igen, akkor nem kell itt semmilyen Firebase-el vagy új Google Sheetel szorakozni, hisz már van egy adatforrásunk, nem? Miért kéne átlapátolni onnan az adatokat egy másikba? Nem-e lehetne-e azt az API-t amit az Agrártámogatásos oldal keretében csináltatok a Sajtóadatbázishoz (amivel a híreket behúzzuk a blog oldalba) kiterjeszteni egy olyan funkcionalitással, hogy legyen mondjuk egy `person/:name` endpoint, ahova az URL-en keresztül beküldöm az emberke nevét és az vissza ad nekem egy JSON választ a kép címével és a szöveggel (azt már a NERHotel alkalmazáson belül tudom trimelni, formázni meg akárhogy masszírozni...)

3) Ha csak az a probléma, hogy a túl hosszú szöveg vizuálisan lenyomja a többi utánakövetkező tartalmat, akkor ezen segíthetünk. Meg lehetne úgy csinálni hogy mondjuk alapból csak 3-4 sornyi szöveg látszik és az ötödiket letakaja egy ilyen fehér áttetsző réteg (kvázi kifade-eljük), aztán ott egy `...` vagy `tovább` gomb, amire rákattinva megjelenik a teljes szöveg. Nem tudom el tudod-e képzelni, hirtelen nem találok rá példát, de pl a Facebookon a hosszú posztoknál a feedben is van hasonló megoldás. Csak azért mert akkor a tartalomgyártóknak nem kell ilyen mindenféle karakterlimiteket figyelembe vennie a Sajtóadatbázis szövegének felvételénél.

**Comment by pisipite** [comment]
1. abszolút nem fontos, ne bajlódj vele!
2. micsoda ötlet! indítok erre egy új issue-t mindjárt.
3. aha, ez tök jó megoldás!

**Comment by Cooty** [comment]
@pisipite Megnéztem, kicsit jobban ezt az API-t és van egy apró probléma:

1) Zsolt ezt írja ` prefix keresést csinál és több találatot ad vissza, mivel az adatbázisban szuffix-ekkel különböztetitek meg a Kovács Lászlókat (alias “Kovács László”) keresésre vissza fogja adni “Kovács László”, “Kovács László (olaj)” és hasonló emberkéket`. Mivel ugye simán lehet két azonos nevű magyar oligarcha, ugye `Kovács László`-ra 8 találat jön vissza.
A probléma az, hogy ez az esetleges szufix, a mi excelünkben nem szerepel, szóval nem tudom összehasonlítani a találatokat a névvel. Én ugye azt a nevet küldeném be neki amit a UI-on is kiírunk fejlécként, tehát ezt:


![Image](https://user-images.githubusercontent.com/6146591/224530672-0afd99f2-e5d5-4ef0-b886-1e3031e899f0.png)

és utána ha erre több találatot kapok, akkor semmi esélyem rá, hogy megtaláljam melyik az "igazi".
Azt tudom javasolni, hogy rakjuk be egy oszlopba a main_oligarch nevét (vagy igazából nem tudom ki az akit mindig kiírunk a UI-on ), mint tulajdonos - bár ugye ez is problémás, mert egy csomó hotelnél több tulaj van és nem pontosan értem a rendszerezést.

A másik lehetőség, hogy az API-t átalakítjuk úgy, hogy valami egyedi azonosítót is tudjon fogadni paraméterként. Tehát `https://adatbazis.k-monitor.hu/api-person.php?id=<UUID>` és akkor mindig csak egy entitást adna vissza válaszként. @juzraai Ez megoldható?

2) Azt hiszem ez igazából az 1)-es ponthoz kapcsolódik, de további probléma, hogy nem mindenki ugyanazon a néven szerepel a NERHoteles excelben, mint a Sajtóadatbázisban, pl [Tiborcz István Ferenc](https://www.nerhotel.hu/person/Tiborcz%20Istv%C3%A1n%20Ferenc) vs [Tiborcz István](https://adatbazis.k-monitor.hu/adatbazis/szemelyek/tiborcz-istvan). Nyilván itt is az a probléma, hogy ha `name` paraméterként beküldöm az API-nak, amit a NERHotelen látok, azaz `Tiborcz István Ferenc`, akkor bizony üres találatot fogok kapni.

3) Mi lesz a nyelviesítéssel? Ha jól tudom a K-Monitoros sajtóadatbázis megújítás előtt áll, ami majd egy angol verzió hozzáadásával is fog járni, ugye? Ha igen akkor majd ezt az API endpointot is nyelviesíteni kellene valamilyen úton módon. Amíg az elkészül természetesen be tudom kötni az API-t úgy hogy angol verzióban egyszerűen nem mutatjuk a személy infóboxát és nem is hívjuk le az adatokat a háttérben (ugye a hiányzó fordításoknál is ez a policy, hogy ha nincs meg angolul valami akkor inkább nem írunk ki semmit).

**Comment by Cooty** [comment]
@juzraai - Van egy kis probléma a `/api-person` endpointal. Kliens-oldali JS-ből szeretném meghívni és a CORS közbeszól.

```
Access to fetch at 'https://adatbazis.k-monitor.hu/api-person.php' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Be tudnád állítani, hogy a response-ban legyen egy `Access-Control-Allow-Origin: *` header?

**Comment by juzraai** [comment]
@Cooty Beraktam a header-t, illetve megcsináltam az ID alapú keresést is (`/api-person.php?id=`). A válasz formátuma ugyanaz, de maximum 1 elem lesz a `results` tömbben. :)

**Comment by Cooty** [comment]
> @Cooty Beraktam a header-t, illetve megcsináltam az ID alapú keresést is (`/api-person.php?id=`). A válasz formátuma ugyanaz, de maximum 1 elem lesz a `results` tömbben. :)

Ohh nagyon király vagy, köszi!
@pisipite - akkor viszont az lenne a teendő, hogy fel kéne vinni annak a személynek az ID-ját az Excel-be aki a "fő oligarcha", vagy nem is tudom pontosan hogy kit írunk ki, talán csináljunk egy callt valamikor a héten, hogy akkor hogy és mit is kéne módosítani a táblázatban

**Comment by pisipite** [comment]
ebben a [másik issue](https://github.com/Code-for-Hungary/nerhotel/issues/58#issue-1596651047)-ban már írtam pár gondolatot erről. arról mit gondolsz, hogy egy spreadsheeten legyenek összekapcsolva a személyek és a hozzájuk kapcsolódó sajtóadatbázis ID-k?

**Comment by Cooty** [comment]
@juzraai - Bekötöttem az ID-s API endpointot, remekül működik. Egy kérdésem/kérésem lenne. Találtam olyan esetet, hogy a kép URL-je (`image_small_url`) 404-et dob. Sajnos ezt kliens oldalon nem tudom elkapni így borken image-t renderelek ki az oldalra. Nem e lehetne e olyat, hogy ilyenkor a `image_small_url` (meg persze a `image_url`) értéke a JSON-ban `null`? Persze ha a backend is csak azt látja, hogy a DB-ben ott van az URL mint érték és ez valahol network vagy file rendszer szinten törik el, akkor persze nem lehet mit csinálni... :( Sajnos nem is tudok példát küldeni a hiba reprodukálására, egy ilyet láttam amikor még az első vezriót tesztelgettem, de sajna már nem emlékszem ki volt az. Talán @pisipite tudja.

Nem nagy gond egyébként, nem kritikus probléma. De ha egyszerű megoldani és van rá időd akkor tök jó lenne.

**Comment by pisipite** [comment]
őrületesen jó vagy!



> * Az adatokat mostmár az excelben felvett ID alapján szedi minden személy oldalán
ez így szuper! próbálgatásaim alapján jónak tűnt mindenhol.
> * Az első 5 sor után elfade-eljük a az utolsó sort és van egy "Tovább..." link ami kinyitja az egészet, majd ez átváltozik "Bezár" linké ami értelemszerűen visszazárja a kártya szövegét. Ha pedig nagyon kevés szöveg van csak (egyszer találtam ilyet, de most nincs előttem a példa), akkor nem is lesz ott ez a kis Tovább link és nincs cropolva a szöveg.
szép! néztem mobilon is, ott is passzol.
> * Megoldottam, hogy ahol nem 1:1 méretarányú kép van ott ne torzuljon hanem középre igazítva rakja ki (persze nem fog olyan jól kinézni, de azért csak nem olyan ronda mintha széthúzná)
oks, ügyelünk rá, hogy egységesek legyenek az adatbázisban a képek.
> * Mivel ez a tartalom csak magyarul érhető el így az angol verzióban nem rakom ki (ellenben ha angolról átváltasz magyarra akkor megjelenik)
ezt az adatbázisban felveszem a wishlistre, hogy legyen ott angol tartalom.
> * Lekezelem az olyan eseteket amikor nincs a táblázatban ID, vagy van de az API-ban nincs szöveg az ember profiljához (talán egy ilyet találtam tök véletlenül)

mehet élesbe!
tényleg nagyon köszi!
