### ISSUE TITLE
Költöztessük át az oldalt Vercelre

### ISSUE THREAD

**Issue by Cooty** [Code-for-Hungary/nerhotel#4]
@gazdagergo javaslata volt, hogy rakjuk át az oldalt [Vercelre](https://vercel.com/).
Ezzel sok olyan problémát meg lehetne oldalni, amit a #3 issue felvet. Ami mindenképpen kéne ehhez, hogy a domain A Recordja a Vercelre mutasson.

@gazdagergo - Tudod vállalni, hogy fel setupols egy verceles repo összekötést, meg az összes szükséges beállítást egy ideiglenes domainel?

**Comment by gazdagergo** [comment]
Megvagyok a költöztetéssel.

Az ideiglenes domain:
https://nerhotel.vercel.app/#/

A nerhotel.hu domain hozzárendeléshez a következő két beállítás szükséges a DNS-rekordokban:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/8988279/205502714-2d8f03b9-687c-4225-984c-4f134f8d603d.png">

Illetve:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/8988279/205502729-6b9effed-1e30-4def-860c-dd0b2986213a.png">

Az SSH (https) tanúsítást a saját tárhelyén a vercel elintézi automatikusan a nerhotel-re, amint megvan az összekötés. Nem tudom, hogy a mostani https tanúsítvány hogy és mint van intézve, de szerintem arra sincs szükség innentől.

**Comment by gazdagergo** [comment]
Ehhez kapcsolódóan még egy feladat lesz:
#14

**Comment by pisipite** [comment]
írtam a domain kezelő Haluska Györgynek. szólok, ha megvan.

**Comment by pisipite** [comment]
működik, szuper!
