### ISSUE TITLE
A Google Analytics nem trackeli rendesen a React SPA aloldalait

### ISSUE THREAD

**Issue by Cooty** [Code-for-Hungary/nerhotel#41]

**Comment by Cooty** [comment]
@pisipite Kiraktam egy módosítást élesre ami **elvileg** megoldja azt a problémánkat, hogy a GA nem látja rendesen az aloldalakat. Ellenben csak Google Analytics fejlesztői eszközzel tudtam tesztelni (ami egy Chrome böngésző kiegészítő ami mutatja mi kerül a GA-nak küldött adat csomagba), de persze nem láttam, hogy ez valóban, hogy jön le a felületen.

A múltkori chatünk óta, amikor mutattál adatokat kicsit el vagyok bizonytalanodva, hogy pontosan hogy is kezeli a GA a JavaScript alapú oldalakat (mert ott ugye láttunk más címkéjű aloldalakat, de valahogy nem tűnt reálisnak a szám). Tök jó lenne, ha adnátok hozzáférést a GA-hoz, hogy a végére tudjak járni ennek és, hogy tesztelni tudjam a most kirakott megoldást.

**Comment by pisipite** [comment]
rendkívül szuper vagy!
adtam hozzáférést a fiókhoz.
a régi GA-ban történt változás, úgy tűnik, méri az oldalakat:
![kép](https://user-images.githubusercontent.com/25430950/219364244-b554a038-caeb-41ed-b316-f406598212dd.png)
viszont az új GA4-ben most mintha kevesebb látszódna (ez lenne a fontosabb, mert a másik a nyáron megszűnik). lehet, hogy én nézem rossz helyen (Oldalak és képernyők)
![kép](https://user-images.githubusercontent.com/25430950/219365286-1ec2b671-d8cd-4c15-ade6-729665efb93c.png)

**Comment by Cooty** [comment]
Láttam adtál hozzáférést, így könnyebb lesz debugolni, hogy mit is csinálok. Nem vagyok nagy GA mágus, de megpróbálom kibogozni.

De egyébként az első screenshot is problémás, mert ott van, hogy 50-en látták a "/" című oldalt, ami ugye a főoldal, de aztán ott van mellette, hogy 7-en látták a "/#/" című oldalt, ami szintén a főoldalt jelenti, csak azután miután beindult a kliens oldali router (azaz a JS alkalmazás), szóval ez sehogy nem jó...

**Comment by Cooty** [comment]
Valószínűleg ez lesz a megoldás a problémánkra
https://www.npmjs.com/package/react-ga

**Comment by Cooty** [comment]
@pisipite Nekem ugy tunik, hogy mukodik.
Ha bemegyek a real-time nezetbe es elkezdek navigalni az oldalon konkretan latom, hogy valaki a fekete tenger partvidekerol, desktop bongeszobol nezegeti az oldalt es (kis csuszassal) valos idoben latom milyen oldak kozott valtogatok



![Image](https://user-images.githubusercontent.com/6146591/219460132-b03af784-e1ae-4cee-9c56-f5a8a6fca150.png)

Egy-ket aprosagot megnezek meg, meg beallitok egy custom eventet arra amikor valaki megnyit egy pop-upot a terkepen (mert az ugye nem oldal megtekintes), meg meg egy kicsi tesztelgetem persze, de ugy nez ki, hogy most jok vagyunk.

**Comment by Cooty** [comment]
@pisipite  Na úgy tűnik megoldottam a dolgot. Az volt amit sejtettem, ha belandoltál közvetlenül teszem azt a https://www.nerhotel.hu/#/hotel/286 aloldalra (mondjuk az FB-n rákattintottál vagy akárhonnan másholról), a GA akkor is a "/" azaz a főoldal URL-jét logolta, hisz a szerver oldalról nézve csak az index.html került kiszolgálásra, minden más JS-ben türtént (mármitn az oldal megjelenítése és az URL változás).

Ezt most megszereltem, úgy hogy eleve a React applikáció indítja el és menedzseli a Google Analyticset.

Továbbá kiszerveztem a GA id-t egy környezeti változóba, ami a Vercel felületén van felvéve (vagy a fejlesztő berakhatja magának localba az env file-ba).
Vercelen úgy állítottam be, hogy csak Production környzetben él a változó. Ennek az a gyakorlati hatása, hogy a fejlesztő helyi gépén meg a Verceles preview címeken nem tölt be az analitika így nem szennyezi az adatokat (hiszen ez nem élő traffic amikor mi ott nézegetjük).

Szintén hozzáraktam egy un. eseményt ami a térképen éppen megnyitott pop-upot követi. Ezt majd a "viselkedése / események" alatt nézhetitek meg a GA felületén.

Teszteld kérlek te is. Ezt az issue-t most lezárom. Ha valami más GA-val kapcsolatos hibát észlelsz vagy plusz kérés van, akkor kérlek nyiss egy újat rá!
