### ISSUE TITLE
személyek tábla kezelése

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/nerhotel#58]
#38 -ban merült fel:

> szövegnél valami limitet jó lenne majd belerakni, hogy pl. csak 320 karaktert szívjon át a sajtóadatbázisból  - Azt mondod "Szívjon át a sajtóadatbázisból...", ez azt jelenti, hogy ez adat (szöveg és profilkép) mindig a K-Monitoros Sajtóadatbázisból jönne? Mert ha igen, akkor nem kell itt semmilyen Firebase-el vagy új Google Sheetel szorakozni, hisz már van egy adatforrásunk, nem? Miért kéne átlapátolni onnan az adatokat egy másikba? Nem-e lehetne-e azt az API-t amit az Agrártámogatásos oldal keretében csináltatok a Sajtóadatbázishoz (amivel a híreket behúzzuk a blog oldalba) kiterjeszteni egy olyan funkcionalitással, hogy legyen mondjuk egy person/:name endpoint, ahova az URL-en keresztül beküldöm az emberke nevét és az vissza ad nekem egy JSON választ a kép címével és a szöveggel (azt már a NERHotel alkalmazáson belül tudom trimelni, formázni meg akárhogy masszírozni...)

kérdés, hogy mi alapján kötjük össze a [beolvasott sheet](https://docs.google.com/spreadsheets/d/1FaeML93U76Fjh9GR7gbQhtb2O3Ga0ZY2honrYKyQQLo/edit?usp=sharing)ből a neveket és a sajtóadatbázis api-ját. legjobb lenne a sajtóadatbázisban a személyek mellett szereplő id-vel. ezen keresztül lehetne áthozni a képet, a szöveget, és a személyhez tartozó url-t (és a személy nevét?).

én így alakítanám át az adatbázis struktúráját:
- [PEP2 sheet](https://docs.google.com/spreadsheets/d/13U-uT201kePIoKaBJMPZqNkYECjAqTyitkgowKYqRPM/edit?usp=sharing) átkerül egy publikus spreadsheetbe. ez tartalmazza a következő oszlopokat: `id` (nerhotelen belüli id, egyelőre használaton kívül), `name` (egyelőre ez alapján kapcsolódhatna össze a hotelek listjája sheettel), `pep` (true/false), `k_id` (sajtóadatbázis api id).
- `pep`: ha igaz, akkor jelölje PEP-nek (most a név előtti !!!-jel működik)
- a [beolvasott sheet](https://docs.google.com/spreadsheets/d/1FaeML93U76Fjh9GR7gbQhtb2O3Ga0ZY2honrYKyQQLo/edit?usp=sharing)ből így kikerülhetne a !!!-ezés.
- a személyek szövegei, képei és sajtóadatbázis linkjei jöhetnének közvetlenül az api-ból

így visszakerül mégis a sheetezés, de cserébe jobban követhető, hogy milyen személyek szerepelnek a nerhotelen (és azok közül ki PEP). ha ez sok, akkor mehetünk azzal is, hogy közvetlenül a hotelek listájában jelöljük a sajtóadatbázis api id-t.

**Comment by pisipite** [comment]
ahhoz, hogy a sajtóadatbázis érkező adat bekapcsolódjon, be kell állítani, hogy a személyek neve, id-je, képe, szövege szerepeljen az API-ban, ugye?
erről írok Jurányi Zsoltnak.

**Comment by pisipite** [comment]
Zsolt írt:
```
Összedobtam ezt:

 API URL: https://adatbazis.k-monitor.hu/api-person.php?name=
 name paraméterben egy személynevet vár
 prefix keresést csinál és több találatot ad vissza, mivel az adatbázisban szuffix-ekkel különböztetitek meg a Kovács Lászlókat (alias “Kovács László”) keresésre vissza fogja adni “Kovács László”, “Kovács László (olaj)” és hasonló emberkéket
 a válasz JSON egy objektum, az alábbi mezőkkel
 name: az input név, amit megadtál
 error: ha hiba van, itt a magyarázat
 results: találatok tömbje, az elemekben az alábbi mezők vannak
- id: személy azonosítószáma
- url: adatbázis adatlap URL
- image_url: arckép URL
- image_small_url: kicsi arckép URL
- name: adatbázisbeli név
- description: adatbázisbeli teaser
- body: adatbázisbeli bodytext
```

**Comment by Cooty** [comment]
@pisipite - Öszintén szólva nem pontosan értem ezt az egész táblázatosdit (mindig csak adatbázisokkal és API-kal dolgoztam ez az Excel mint adatbázis valahogy nem fér a fejembe)... Jobban neki kell ülnöm kicsit jobban megérteni, hogy is függnek össze a személyek a hotelekkel, szóval nem tom biztos, jó ez a megoldás amit javasolsz, csak én egyszerűen **nem értem**. Esetleg csináljunk egy callt, ahol screen sharingel elmagyarázod ezt nekem.

**Comment by pisipite** [comment]
a beszéltek alapján a következő rendszer a következő lépés:
- a publikus [spreadsheet táblába](https://docs.google.com/spreadsheets/d/1FaeML93U76Fjh9GR7gbQhtb2O3Ga0ZY2honrYKyQQLo/edit#gid=0) bekerül 3+5 új oszlop T1_ID, T2_ID, stb.
- ezekbe a tulajdonosnak, illetve cégvezetőnek (T1 OL, IT1, stb.) megfelelő k-monitor sajtóadatbázisban szereplő személy id-i kerülnek.

ezt most összeraktam, az új oszlopok az AG-AN közé kerültek.
raktam bele ID-ket is, valószínű még fogok újakat.
