### ISSUE TITLE
ner hotel > hotel oligarch

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/nerhotel#67]
magyarul nem tudó közönség számára már egy ideje hotel oligarch-ként hivatkoztunk az oldalra. ezt lenne szuper átvinni az oldalra is. kb. az alábbiakat gondolom:

- [x] tartalom átírása, nerhotel magyarázat az aboutban és a címsorban.
- [x] domain lefoglalása és átirányítása.
- [x] angol verzióban a logó lecserélése [erre](https://github.com/Code-for-Hungary/nerhotel/blob/master/src/assets/nh-logo-en.svg). vagy ez túl nagy macera, mert akkor itt is kettőzni kell?

első kettőn én rajta vagyok, harmadikban leginkább @Cooty -ra számítok.

**Comment by Cooty** [comment]
@pisipite - nem, nem nagy macera egyáltalán, ha jól látom ez a logó egy az egyben ugyanaz a méret arány, mint a magyar.

Ugye jól értem úgy képzeled el, hogy az angolul beszélő usernek küldtök egy linket, hogy `https://www.hotel-oligarch.hu/person/Klemm%20Bal%C3%A1zs%20Lajos?plang=en` és az átdobja a `https://www.nerhotel.hu/person/Klemm%20Bal%C3%A1zs%20Lajos?plang=en` címre, ugye?

**Comment by Cooty** [comment]
@pisipite az aloldalakon, amikor a logo kis méretre vált, nem nagyon lehet elolvasni a feliratot. Illetve mintha a méret is kicsit más lenne, mert amikor nyelvet váltok, akkor egy kicsit "ugrál" a logo. De mivel ezt a képet raktad be ezért egyelőre ezzel kell dolgoznom, szóval kirakom így élesre aztán majd lehet még rajta reszelni

![image](https://user-images.githubusercontent.com/6146591/224509839-15fa31de-7d86-43e8-8dfd-f6b499e475df.png)

**Comment by pisipite** [comment]
szuper, köszi szépen!
aha, ez még csak egy  próba kép volt. frissítettem egy pontosabbal.

domain kapcsán az első változat (átírányítás) működőképes?
igazából minimál megoldásnak az is elégséges, hogy csak a holtel-oligarch.com átvisz a nerhotel.hu-ra. a lefoglalással kb. az a cél, hogy aki beírja a böngészőbe, az rátaláljon (linkeket meg küldhetünk nerhotel.hu-s domainnel).

**Comment by Cooty** [comment]
> 

Aha, az első verzió tökre lehetséges :)
És ezt általában a domain szolgáltató szintjén szokták elintézni (tehát nekem nem kéne kódot írjak erre).
Itt egy jó leírás arról, hogy [pl a Namecheap felületén](https://www.namecheap.com/support/knowledgebase/article.aspx/385/2237/how-to-redirect-a-url-for-a-domain/), hogyan kell ezt elintézni, de mindenképp a domain szolgáltatónál kell ezt beállítani valahogy.

**Comment by pisipite** [comment]
szuper!
egyelőre sima átirányítást beállítottam, tisztább fejjel majd próbálom ezt is. köszi!
