### ISSUE TITLE
Licensz hozzáadása

### ISSUE THREAD

**Issue by Cooty** [Code-for-Hungary/nerhotel#8]
Az about oldalon azt írjuk

> Az eszköz [nyílt forráskóddal](https://github.com/Code-for-Hungary/nerhotel) rendelkezik, így szabadon továbbfejleszthető, alakítható és felhasználható.

Ez hazugság ugyanis a repository nem rendelkezik semmilyen licensz file-al, a kódban sincs sehol licensz megjelölés. Tehát jogi szempontból nem rendelkezik nyílt forráskóddal.

**Comment by Cooty** [comment]
@pisipite Pusztán annyi kéne, hogy ki kéne találni milyen Open Source licenszet válasszunk. Ez link [segít dönteni](https://choosealicense.com/). Én [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) licenszt ajánlanám, de döntsük el.

**Comment by pisipite** [comment]
[GPL3.0](https://spdx.org/licenses/GPL-3.0.html)-át használjuk máshol is (pl. a [költségvetés vizu](https://kozertheto.k-monitor.hu) ), ez jó lesz!
