### ISSUE TITLE
Bizonyos képernyőméreteken a logó rátakar a menü ikonra

### ISSUE THREAD

**Issue by Cooty** [Code-for-Hungary/nerhotel#9]
![image](https://user-images.githubusercontent.com/6146591/205498927-b04bf9d8-ae0e-4615-8e19-7ee87e9d5cd7.png)

![image](https://user-images.githubusercontent.com/6146591/205498947-58b17831-c01c-47df-901c-46c8fad4843c.png)

Reprodukálás lépései:
- Nyisd meg bármelyik oldalt 1070 és 480px közötti képernyőméretben

Következmény:
- Ezekben a méretekben a menü ikon nem kattintható, a user nem tud hozzáférni a navigációhoz, ha pl egy állított iPaden nézi az oldalt

Megoldás:
- A menü ikonnak minden méretnél látszódnia kell

**Comment by Cooty** [comment]
fixálva: [itt](https://nerhotel-775tnpntb-c4hu.vercel.app/) lehet megnézni.

**Comment by pisipite** [comment]
szuper, kösz!
